# Generated by Django 5.1.6 on 2025-03-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("text", models.CharField(max_length=5000)),
                (
                    "audio",
                    models.FileField(null=True, upload_to="uploads/audio/%Y/%m/"),
                ),
                (
                    "english_audio",
                    models.FileField(null=True, upload_to="uploads/audio/%Y/%m/"),
                ),
                (
                    "image",
                    models.ImageField(null=True, upload_to="uploads/image/%Y/%m/"),
                ),
            ],
        ),
    ]
