# Generated by Django 5.1.6 on 2025-06-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Characters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character", models.CharField(max_length=10)),
                ("timestamp", models.TimeField(auto_now_add=True)),
                ("right_count", models.IntegerField()),
            ],
        ),
    ]
