# Generated by Django 5.1.6 on 2025-06-20 22:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_game", "0002_characters"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Characters",
            new_name="Character",
        ),
    ]
